server :
  port : 8088

logging:
  level:
    org.springframework : DEBUG


spring:
  messages:
    basename: messages
    fallback-to-system-locale: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
#  security:
#    user:
#      name: username
#      password : passw0rd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enable: true
      settings:
        web-allow-others: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

